name: (Pre-)Release

on:
  create:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: Create Package Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: Gr1N/setup-poetry@v9
    - run: poetry --version
    - name: Build package
      run: poetry build
    - name: Create Pre-Release
      if: ${{ endsWith( github.ref_name, 'pre' )}}
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: true
        files: |
          dist/*
    - name: Create Release
      if: ${{ !endsWith( github.ref_name, 'pre' )}}
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: false
        files: |
          dist/*
